# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 731c982e0ff544cc43838c25944d332261883a3c41cbf7bc21b263c2e389413a57de2eb69403fa645949ea60919b13e9e012c62be274e5375ef4802aeb5d1da8

test:
  secret_key_base: 883341f317c291fff2362c301770ba327af5c72ce18ed9e1cd93c2331ab2159e72ff8ff0075ed7565672f9312ddd2fae196f153b2214552e20c76138ba6821ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
